const FeedNews = [
    {
        id: 'VLXX1',
        username: 'Hoàn',
        image: require("../../../assets/images/dalat2.jpg"),
        avatar: require("../../../assets/images/avatar3.png"),
        date: '20/02/2020',
        rating: 4,
        places: 'TP.Hồ Chí Minh - Đà Lạt',
        title: 'Trải nghiệm đáng nhớ',
        hastag: ['#tphcm', '#dalat'],
        content: 'Có thể nói đây là một trong những chuyến du lịch tuyệt vời nhất mà mình từng đi. Hà Nội, thành phố mà...',
        price: '3.000.000',
        love: 1234,
        comment: 1234,
    },
    {
        id: 'VLXX2',
        username: 'Nam ngu si',
        avatar: require("../../../assets/images/avatar.png"),
        image: require("../../../assets/images/vinhhalong.jpeg"),
        date: '20/02/2020',
        rating: 5,
        places: 'TP.Hồ Chí Minh - Hạ Long',
        title: 'Kỷ niệm khó phai',
        hastag: ['#tphcm', '#halong'],
        content: 'Có thể nói đây là một trong những chuyến du lịch tuyệt vời nhất mà mình từng đi. Hà Nội, thành phố mà...',
        price: '2.000.000',
        love: 1234,
        comment: 1234,
    },
    {
        username: 'Ai Đó',
        id: 'VLXX3',
        avatar: require("../../../assets/images/avatar2.png"),
        image: require("../../../assets/images/vungtau.jpg"),
        date: '20/02/2020',
        rating: 4,
        places: 'TP.Hồ Chí Minh - Vũng Tàu',
        title: 'Nắng nóng vãi l**',
        hastag: ['#tphcm', '#vungtau'],
        content: 'Có thể nói đây là một trong những chuyến du lịch tuyệt vời nhất mà mình từng đi. Hà Nội, thành phố mà...',
        price: '1.000.000',
        love: 1234,
        comment: 1234,
    },
]

export { FeedNews };